FROM ubuntu:24.04

RUN apt update && apt install -y    \
    build-essential                 \
    cmake                           \
    wget                            \
    tar                             \
    graphviz

RUN wget https://github.com/doxygen/doxygen/releases/download/Release_1_15_0/doxygen-1.15.0.linux.bin.tar.gz \
    && tar -xzf doxygen-1.15.0.linux.bin.tar.gz -C /usr/local \
    && rm doxygen-1.15.0.linux.bin.tar.gz

ENV PATH="/usr/local/doxygen-1.15.0/bin:${PATH}"
